### ISSUE TITLE
Makefile enforces use of virtualenv and uses hardcoded 'python3' environment name and enforces own requirements

### ISSUE THREAD

**Issue by casperfrx** [krukas/Trionyx#39]
Can't run Makefile right now (without editting) to use current python (for example in a Docker file).

**Comment by krukas** [comment]
Haven't use Docker, do you need to give the full path to Python with docker? Normally python3 is a symlink to default version on the system. But indeed if you want to use a different version on the same system it not hardcoded to your system default. We could add options that you can specify witch version you want to use that defaults to default system version.

Are you talking about the Makefile that is generated with make_project? The idea was to generate a fully working project. If you want to manage your requirements differently you can change that and update you project Makefile.

**Comment by krukas** [comment]
@casperfrx Fixed with version 2.0.1
